services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: toto

  api:
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
    environment:
      - DB_PASSWORD=toto
    ports:
      - 5734:80      

  web:
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    ports:
      - 5735:5173      

  init:
    profiles: [setup]
    image: mysql
    command: sh -c 'mysql -h db --password="toto" avatar < /var/db_init'
    configs:
      - source: db_init
        target: /var/db_init
    depends_on:
      - db

configs:
  db_init:
    file: init.sql  