services:
  db:
    image: mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db_password)" --silent
      interval: 1s
      retries: 10
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: toto
    networks:
      - private

  api:
    image: avatar-api
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
    environment:
      - DB_PASSWORD=toto
    networks:
      - private
    ports:
      - 5734:80
    depends_on:
      db:
        condition: service_healthy  

  web:
    image: avatar-web
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    networks:
      - private
      - public
    ports:
      - 5735:5173
    depends_on:
      - api

networks:
  private:
    internal: true
  public: