services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: toto

  api:
    build: server
    platform: wasi/wasm32
    runtime: io.containerd.wasmedge.v1
    ports:
      - 5734:80

  web:
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    ports:
      - 5735:5173
