services:
  db:
    image: mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent
      interval: 1s
      retries: 10
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - db_data:/var/lib/mysql  
    networks:
      - private

  api:
    image: avatar-api
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
    secrets:
      - db-password
    networks:
      - private
    ports:
      - 5734:80
    depends_on:
      db:
        condition: service_healthy  

  web:
    image: avatar-web
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    networks:
      - private
      - public
    ports:
      - 5735:5173
    depends_on:
      - api

volumes:
  db_data:

secrets:
  db-password:
    file: ~/.DB_SECRET

networks:
  private:
    internal: true
  public:
