services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: toto

  api:
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
      platforms:
      - linux/arm64
      - linux/amd64
      - linux/386

    environment:
      - DB_PASSWORD=toto
    ports:
      - 5734:80      

  web:
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    ports:
      - 5735:5173