services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: toto

  api:
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
    x-develop:
      watch:
        - path: api/requirements.txt
          action: rebuild
        - path: api/
          target: /app/api/
          action: sync      
    environment:
      - DB_PASSWORD=toto
    ports:
      - 5734:80      

  web:
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    x-develop:
      watch:
        - path: web/package.json
          action: rebuild
        - path: web/yarn.lock
          action: rebuild
        - path: web/
          target: /app
          action: sync      
    ports:
      - 5735:5173      