services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: toto
    volumes:
      - db_data:/var/lib/mysql  

  api:
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
    environment:
      - DB_PASSWORD=toto
    ports:
      - 5734:80      
    volumes:
      - ./api:/app/api

  web:
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    ports:
      - 5735:5173      

volumes:
  db_data:      