services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: toto
    networks:
      - private

  api:
    image: avatar-api
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
    environment:
      - DB_PASSWORD=toto
    networks:
      - private
    ports:
      - 5734:80      

  web:
    image: avatar-web
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    networks:
      - private
      - public
    ports:
      - 5735:5173

networks:
  private:
    internal: true
  public: