services:
  db:
    image: mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db_password)" --silent
      interval: 1s
      retries: 10
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql        
    secrets:
      - db_password      
    networks:
      - private

  api:
    build: server
    platform: wasi/wasm32
    runtime: io.containerd.wasmedge.v1
    ports:
      - 5734:80
    networks:
      - private

  web:
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    x-develop:
      watch:
        - path: web/package.json
          action: rebuild
        - path: web/yarn.lock
          action: rebuild
        - path: web/
          target: /app
          action: sync       
    networks:
      - private
      - public
    ports:
      - 5735:5173
    depends_on:
      - api

  init:
    profiles: [setup]
    image: mysql
    command: sh -c 'mysql -h db --password="$$(cat /run/secrets/db_password)" avatar < /var/db_init'
    secrets:
      - db_password      
    configs:
      - source: db_init
        target: /var/db_init
    networks:
      - private
    depends_on:
      - db

configs:
  db_init:
    file: init.sql       

volumes:
  db_data:

secrets:
  db_password:
    file: ~/.DB_SECRET

networks:
  private:
    internal: true
  public:
