services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password      

  api:
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
    secrets:
      - db_password
    ports:
      - 5734:80      

  web:
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
    ports:
      - 5735:5173

secrets:
  db_password:
    file: ~/.DB_SECRET
