services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: avatar
      MYSQL_ROOT_PASSWORD: toto

  api:
    image: gloursdocker/avatars-api
    build:
      context: .
      dockerfile: ./deploy/api.dockerfile
      ssh:
        - default
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      - DB_PASSWORD=toto
    ports:
      - 5734:80      

  web:
    image: gloursdocker/avatars-web
    build:
      context: .
      dockerfile: ./deploy/web.dockerfile
      target: production
      platforms:
        - linux/amd64
        - linux/amr64
    ports:
      - 5735:80